import js from '@eslint/js';
import globals from 'globals';
import tseslint from 'typescript-eslint';
import reactHooks from 'eslint-plugin-react-hooks';
import reactRefresh from 'eslint-plugin-react-refresh';
import prettier from 'eslint-config-prettier';

// NOTE (Chunk 01): `npm create vite@latest` installed ESLint 10, but eslint-plugin-react@7
// does not yet support ESLint 10 (peer range tops out at ^9.7). Per the human's decision we
// keep ESLint 10 and drop eslint-plugin-react. Every required rule is preserved: no-explicit-any
// and ban-ts-comment via typescript-eslint, no-console via core, and the react-hooks rules via
// eslint-plugin-react-hooks (which DOES support ESLint 10). See /context/decisions.md.
export default tseslint.config(
  { ignores: ['dist', 'node_modules'] },
  {
    files: ['**/*.{ts,tsx}'],
    extends: [
      js.configs.recommended,
      ...tseslint.configs.strictTypeChecked,
      reactHooks.configs.flat.recommended,
      reactRefresh.configs.vite,
    ],
    languageOptions: {
      ecmaVersion: 2022,
      globals: globals.browser,
      parserOptions: {
        project: ['./tsconfig.json', './tsconfig.node.json'],
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/ban-ts-comment': [
        'error',
        {
          'ts-ignore': 'allow-with-description',
          'ts-expect-error': 'allow-with-description',
          minimumDescriptionLength: 10,
        },
      ],
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      // Allow numbers in template literals (the rule's own default). react-hook-form field-array
      // names require a number in a template (e.g. `targets.${number}.weeklyTarget`); numbers
      // stringify unambiguously, so this is safe.
      '@typescript-eslint/restrict-template-expressions': ['error', { allowNumber: true }],
      'no-console': 'error',
    },
  },
  // logger.ts is the ONLY file allowed to call console.*
  {
    files: ['src/lib/logger.ts'],
    rules: { 'no-console': 'off' },
  },
  // shadcn/ui primitives are vendored (generated by the shadcn CLI). They legitimately co-export
  // variants/hooks alongside components, which trips react-refresh's fast-refresh rule. We relax
  // that DX-only rule for the vendored folder; correctness rules (no-explicit-any, etc.) stay on.
  {
    files: ['src/components/ui/**/*.{ts,tsx}'],
    rules: { 'react-refresh/only-export-components': 'off' },
  },
  prettier,
);
